# File: .github/workflows/post.yml

on:
  push:
    branches:
    - master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: muathye/portal/pull-request@v2
      with:
        destination_branch: "develop"
        github_token: ${{ secrets.GITHUB_TOKEN }}
