# File: .github/workflows/post.yml
name: Post

on: push

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create pull request
      uses: muath-ye/pr-action@v1.0.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: '/'
        destination_repo: 'muathye/portal'
        destination_folder: 'docs'
        destination_base_branch: 'develop'
        destination_head_branch: 'post'
        user_email: 'muath.ye@gmail.com'
        user_name: 'muath-ye'
        pull_request_reviewers: 'muath-ye'
